In [1]:
import pandas as pd
import numpy as np
data =  pd.read_excel("C:\\Users\\SHREYAS N\\Documents\\Sales Quotation Sample Dataset.xlsx", sheet_name = "Sheet1")

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Product_ID                        25 non-null     object
 1   Sales Quotation                   25 non-null     int64
 2   Converted Quotation               25 non-null     int64
 3   Conversion Rate                   25 non-null     float64
 4   Quotation Item Qty                25 non-null     int64
 5   Open Quotation                    25 non-null     int64
 6   No of Open Items                  25 non-null     int64
 7   Expired Quotation                 25 non-null     int64
 8   No. of Expired Items              25 non-null     int64
 9   Expiring Quotations               25 non-null     int64
 10  No. of Expiring Items             25 non-null     int64
 11  Rejected Quotations               25 non-null     int64
 12  No. of Rejected Items             25 non-null     int64
 13  Inquiry Channel                   25 non-null     object
 14  Predicted Conversion Probability  0 non-null      float64
dtypes: float64(2), int64(11), object(2)
memory usage: 3.1+ KB

In [3]:
data.head()

,Product_ID,Sales Quotation,Converted Quotation,Conversion Rate,Quotation Item Qty,Open Quotation,No of Open Items,Expired Quotation,No. of Expired Items,Expiring Quotations,No. of Expiring Items,Rejected Quotations,No. of Rejected Items,Inquiry Channel,Predicted Conversion Probability
0,MetalProduct1,50000,40000,0.800000,100,10000,10,0,0,5000,30,10000,50,Email,NaN
1,MetalProduct1,100000,100000,1.000000,300,0,0,0,0,0,0,0,0,Internal Sales Lead-PersonA,NaN
2,MetalProduct2,500000,40000,0.080000,874,460000,10,0,0,46000,30,10000,50,Email,NaN
3,MetalProduct2,7896666,105667,0.013381,700,7790999,600,0,0,700000,500,0,0,Internal Sales Lead-PersonA,NaN
4,MetalProduct1,580000,400000,0.689655,456,180000,10,60000,56,12000,100,5000,50,Email,NaN

In [4]:
data.corr()

,Sales Quotation,Converted Quotation,Conversion Rate,Quotation Item Qty,Open Quotation,No of Open Items,Expired Quotation,No. of Expired Items,Expiring Quotations,No. of Expiring Items,Rejected Quotations,No. of Rejected Items,Predicted Conversion Probability
Sales Quotation,1.000000,0.949361,0.219222,-0.186828,0.229494,0.025154,-0.238501,-0.259965,0.088253,-0.075525,-0.341906,-0.410992,NaN
Converted Quotation,0.949361,1.000000,0.364682,-0.267801,-0.087836,-0.097740,-0.163155,-0.177704,-0.079013,-0.227794,-0.224662,-0.273721,NaN
Conversion Rate,0.219222,0.364682,1.000000,-0.670875,-0.437033,-0.490841,0.173199,0.239430,-0.343793,-0.776507,0.234301,0.314250,NaN
Quotation Item Qty,-0.186828,-0.267801,-0.670875,1.000000,0.234918,0.270085,-0.322591,-0.344704,0.241763,0.619012,-0.005702,-0.187950,NaN
Open Quotation,0.229494,-0.087836,-0.437033,0.234918,1.000000,0.381043,-0.244024,-0.267681,0.523767,0.463578,-0.388721,-0.452433,NaN
No of Open Items,0.025154,-0.097740,-0.490841,0.270085,0.381043,1.000000,-0.296471,-0.316794,-0.088470,0.454036,-0.441910,-0.520983,NaN
Expired Quotation,-0.238501,-0.163155,0.173199,-0.322591,-0.244024,-0.296471,1.000000,0.935850,-0.267139,-0.444131,0.089193,0.569061,NaN
No. of Expired Items,-0.259965,-0.177704,0.239430,-0.344704,-0.267681,-0.316794,0.935850,1.000000,-0.286223,-0.474575,0.095307,0.608069,NaN
Expiring Quotations,0.088253,-0.079013,-0.343793,0.241763,0.523767,-0.088470,-0.267139,-0.286223,1.000000,0.547405,-0.400341,-0.471566,NaN
No. of Expiring Items,-0.075525,-0.227794,-0.776507,0.619012,0.463578,0.454036,-0.444131,-0.474575,0.547405,1.000000,-0.424151,-0.590769,NaN
Rejected Quotations,-0.341906,-0.224662,0.234301,-0.005702,-0.388721,-0.441910,0.089193,0.095307,-0.400341,-0.424151,1.000000,0.848224,NaN
No. of Rejected Items,-0.410992,-0.273721,0.314250,-0.187950,-0.452433,-0.520983,0.569061,0.608069,-0.471566,-0.590769,0.848224,1.000000,NaN
Predicted Conversion Probability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data = pd.get_dummies(data)

In [6]:
data.head()

,Sales Quotation,Converted Quotation,Conversion Rate,Quotation Item Qty,Open Quotation,No of Open Items,Expired Quotation,No. of Expired Items,Expiring Quotations,No. of Expiring Items,Rejected Quotations,No. of Rejected Items,Predicted Conversion Probability,Product_ID_MetalProduct1,Product_ID_MetalProduct2,Product_ID_MetalProduct3,Inquiry Channel_Email,Inquiry Channel_Internal Sales Lead-PersonA
0,50000,40000,0.800000,100,10000,10,0,0,5000,30,10000,50,NaN,1,0,0,1,0
1,100000,100000,1.000000,300,0,0,0,0,0,0,0,0,NaN,1,0,0,0,1
2,500000,40000,0.080000,874,460000,10,0,0,46000,30,10000,50,NaN,0,1,0,1,0
3,7896666,105667,0.013381,700,7790999,600,0,0,700000,500,0,0,NaN,0,1,0,0,1
4,580000,400000,0.689655,456,180000,10,60000,56,12000,100,5000,50,NaN,1,0,0,1,0

In [7]:
data = data.drop(["Predicted Conversion Probability"], axis=1)

In [8]:
data[['Conversion Rate']] = data[['Conversion Rate']]*100

In [9]:
X = data[['Conversion Rate']]
#Y = data['Converted Quotation','Sales Quotation', 'Expiring Quotations', 'Product_ID_MetalProduct1','Product_ID_MetalProduct2', 'Product_ID_MetalProduct3', 'Inquiry Channel_Email','Inquiry Channel_Internal Sales Lead-PersonA' ]

In [10]:
Y = data[['Sales Quotation', 'Expiring Quotations', 'Product_ID_MetalProduct1','Product_ID_MetalProduct2', 'Product_ID_MetalProduct3', 'Inquiry Channel_Email','Inquiry Channel_Internal Sales Lead-PersonA'] ]

In [11]:
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [12]:
X_train, X_test, y_train, y_test = train_test_split(Y, X, test_size=0.2, random_state=42)

In [13]:
regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
#To retrieve the intercept:
print(regressor.intercept_)

#For retrieving the slope:
print(regressor.coef_)

[46.20728657]
[[ 5.01585511e-07  2.10032593e-07  3.82620247e+01 -3.88952826e+01
   6.33257954e-01  4.72733446e+00 -4.72733446e+00]]

In [15]:
predictions = regressor.predict(X_test)
predictions

array([[79.91528845],
       [12.07407918],
       [89.22277512],
       [51.80969018],
       [89.22720787]])

In [21]:
# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# predicting the accuracy score
score=r2_score(y_test,predictions)

print('r2 socre is' ,score)

print('mean_sqrd_error is==',mean_squared_error(y_test,predictions))
print('root_mean_squared error of is==',np.sqrt(mean_squared_error(y_test,predictions)))

r2 socre is 0.8848592486849004
mean_sqrd_error is== 115.7652401809158
root_mean_squared error of is== 10.759425643635248

In [60]:
print("Actual","Predicted", y_test,predictions )

Actual Predicted     Conversion Rate
8         99.000099
16         8.000000
0         80.000000
23        50.000000
11        78.755172 [[80.64382447]
 [13.27587995]
 [87.4252554 ]
 [50.5575035 ]
 [87.42752498]]

In [22]:
import pickle 
pickle_out = open("classifier.pkl", mode = "wb") 
pickle.dump(regressor, pickle_out) 
pickle_out.close()